[package]
name = "device-api"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures = "0.3"
# serde-wasm-bindgen = "0.1"
wasm-bindgen = { version = "0.2.58", features = ["serde-serialize", "nightly"] }
# js-sys = "0.3"
wasm-bindgen-futures = "0.4.8"
serde = { version = "1", features = ["derive"] }
# log = "0.4"
tower-service = "0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3.8"
