[package]
name = "lifegame"
version = "0.1.0"
edition = "2018"


[lib]
crate-type = ["cdylib", "rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#thiserror = "1"
frunk = "0.4"
#anyhow = "1"
wasm-bindgen ={version =  "0.2", features=["serde-serialize"]}
js-sys = "0.3"
web-sys = {version="0.3", features=["console","CanvasRenderingContext2d","HtmlCanvasElement", "HtmlBodyElement", "Window", "Document"] }
futures = "0.3"
wasm-bindgen-futures = "0.4"
serde_json = "1"
serde = {version ="1", features =["derive"] }
#proptest = "1"
console_error_panic_hook = "0.1"
lazy_static = "1.4"
