[package]
name = "ndjson-async-stream"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-stream = "0.1"
rayon = "1"
crossbeam = "0.8"
flume = "0.10"
