[package]
name = "wasm-sandbox"
version = "0.1.0"
authors = ["legokichi"]
edition = "2018"


# [lib]
# crate-type = ["cdylib", "rlib"]

# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
# async-trait = "0.1"
# console_error_panic_hook = { version = "0.1.1", optional = true }
# console_log = "0.1"
# futures = "0.3"
# js-sys = "0.3"
# log = "0.4"
# reqwest = { version = "0.10", features = ["json", "cookies", "gzip", "stream", "rustls"], no-default-features = "true" }
# serde = { version = "1", features = ["derive"] }
# serde-wasm-bindgen = "0.1"
# wasm-bindgen = { version = "0.2", features = ["serde-serialize", "nightly"] }
# wasm-bindgen-futures = "0.4"
# wasm-logger = "0.2"
# web-sys = { vesrion = "0.3", features = ["console"] }
# wee_alloc = { version = "0.4.2", optional = true }
# wasm-bindgen-console-logger = "0.1"

# [dev-dependencies]
# wasm-bindgen-test = "0.3"

# [profile.release]
# lto = true
# opt-level = "z"
# # Tell `rustc` to optimize for small code size.
# # opt-level = "s"

# [features]
# default = ["wee_alloc", "console_error_panic_hook"]

