[package]
name = "dockworker-test"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dockworker = {path="../../dockworker"}
tokio = {version = "0.2", features=["full"]}
futures = "0.3"