[package]
name = "gst-webrtc"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
# dotenv = "0.13"
# env_logger = "0.6"
# envy = "0.4"
# failure = "0.1"
# futures = "0.1"
# gstreamer-webrtc = "0.13.0"
# log = "0.4"
# mdo = "0.3"
# mdo-future = "0.2"
# serde = "1"
# serde_derive = "1"
# serde_json = "1"
# servo-media = { git = "https://github.com/servo/media/" }
# servo-media-auto = { git = "https://github.com/servo/media/" }
# servo-media-dummy = { git = "https://github.com/servo/media/" }
# tokio = "0.1"
# tokio-timer = "0.2"
# tokio-tungstenite = "0.6"
# tungstenite = "0.6"
# url = "1.7"
# url_serde = "0.2"
# uuid = { features = ["serde", "v4"], version = "0.6" }
# websocket = "0.20"
