[package]
name = "tokio-console-sandbox"
version = "0.1.0"
edition = "2021"

[build]
debug = 1

[dependencies]
tokio = { version = "1", features = ["full", "tracing"] }
tracing = "0.1"
tracing-subscriber = "0.3"
log = "0.4"
futures = "0.3"
async-stream = "0.3"
tokio-stream = "0.1"
console-subscriber = "0.1"
