[package]
name = "tokio-console-sandbox"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["--cfg", "tokio_unstable"]
debug = 1

[dependencies]
tokio = { version = "1.15", features = ["full", "tracing"] }
tracing = "0.1"
tracing-subscriber = "0.3"
axum = { version = "0.5" }
#tracing-log = { version = "0.1", features = ["env_logger"] }
log = "0.4"
