[package]
name = "lambda-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.4"
serde_json = "1"
serde = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1"

