[package]
name = "strace-sandbox"
version = "0.1.0"
license = "MIT"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
warp = "0.2"
tracing = "0.1"
tracing-subscriber = "0.2"
hyper = "0.13"
rweb = { version = "0.5", features = ["openapi"] }
serde_json = "1"
