[package]
name = "tw-fav"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
dotenv = "0.15"
egg-mode = "0.16"
env_logger = "0.10"
envy = "0.4"
thiserror = "1"
futures = { version = "0.3", features = [] }
log = "0.4"
reqwest = "0.11"
rustyline = "10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = "4"
tokio = { version = "1", features = ["full"] }

