[package]
name = "device-api-b"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
aws_lambda_events = "0.4"
base64 = "0.13"
base64-serde = "0.6"
bitflags = "1"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
derive_more = "0.99"
dotenv = "0.15"
enum-as-inner = "0.3"
env_logger = "0.8"
envy = "0.4"
frunk = { version = "0.3", features = ["serde"] }
frunk_core = { version = "0.3", features = ["serde"] }
futures = "0.3"
hyper = { version = "0.14", features = ["http2"] }
ipnetwork = "0.18"
js_option = "0.1"
lambda_runtime = "0.3"
log = "0.4"
lz4 = { version = "1", optional = true }
lz4_flex = { version = "0.8", optional = true }
msgpack-schema = "0.3"
rmp-serde = { version = "0.15" }
rmpv = { version = "0.4", features = ["with-serde"] }
rusoto_cognito_identity = { version = "0.46", default_features = false, features = ["rustls"] }
rusoto_core = { version = "0.46", default_features = false, features = ["rustls"] }
rusoto_credential = "0.46"
rusoto_dynamodb = { version = "0.46", default_features = false, features = ["rustls"] }
rusoto_ecr = { version = "0.46", default_features = false, features = ["rustls"] }
rusoto_iot = { version = "0.46", default_features = false, features = ["rustls"] }
rusoto_iot_data = { version = "0.46", default_features = false, features = ["rustls"] }
rusoto_sts = { version = "0.46", default_features = false, features = ["rustls"] }
sentry = { version = "0.22", default_features = false, features = ["backtrace", "contexts", "panic", "reqwest", "log", "rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smart-default = "0.6"
strum = { version = "0.21", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
url = { version = "2.2" }
uuid = { version = "0.8", features = ["serde", "v4"] }
void = "1"

[dev-dependencies]
assert-json-diff = "2.0"
canonical_json = "0.4"
insta = { version = "1.7", features = ["ron"] }
mockall = "0.9"
openssl = "0.10"
proptest = "1.0"
proptest-derive = "0.3"
rstest = "0.10"
rumqttc = "0.8"
rusoto_lambda = { version = "0.46", default_features = false, features = ["rustls"] }
rustls = "0.19"

[features]
default = ["lz4"]
e2e = []

[[bin]]
name = "kinesis_lambda"
path = "bin/kinesis_lambda.rs"
required-features = []

[[bin]]
name = "sentry"
path = "bin/sentry.rs"
required-features = []
