[package]
name = "protobuf-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "2", features = ["with-bytes"] }
prost = "0.7"
prost-types = "0.7"
serde = { version = "1", fetatures = ["derive"] }

[build-dependencies]
protoc-rust = "2.0"
