[package]
name = "mqtt-pah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["paho"]
paho = ["paho-mqtt", "paho-mqtt-sys", "tempfile"]
rumqtt = ["rumqttc", "rustls-pemfile"]

[dependencies]
anyhow = "1"
futures = "0.3"
log = "0.4"
paho-mqtt = { version = "0.12", features = ["bundled", "build_bindgen"], optional = true }
paho-mqtt-sys = { version = "0.8", optional = true }
rumqttc = { version = "0.22", optional = true }
rustls-pemfile = { version = "1.0", optional = true }
tempfile = { version = "3.6.0", optional = true }
tokio = { version = "1", features = ["full"] }
env_logger = "0.10"
