[package]
name = "rusoto-s3-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0"
rusoto_s3 = "0"
tokio = "1"
